# Generated by Django 4.2.7 on 2026-03-22 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('energy', 'Energy'), ('transport', 'Transport'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('chemical', 'Chemical'), ('mining', 'Mining'), ('tech', 'Technology'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending KYB'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=42)),
                ('credit_balance', models.IntegerField(default=0)),
                ('carbon_credit_score', models.FloatField(default=0.0)),
                ('permitted_emission_limit', models.FloatField(default=0.0)),
                ('daily_trading_limit', models.IntegerField(default=50)),
                ('credits_traded_today', models.IntegerField(default=0)),
                ('last_trading_reset', models.DateField(blank=True, null=True)),
                ('esg_score', models.FloatField(default=0.0)),
                ('sustainability_initiatives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EmissionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_year', models.IntegerField()),
                ('submission_period', models.CharField(max_length=20)),
                ('total_co2_emissions', models.FloatField()),
                ('energy_consumption', models.FloatField(default=0)),
                ('fuel_consumption', models.FloatField(default=0)),
                ('production_volume', models.FloatField(default=0)),
                ('renewable_energy_percentage', models.FloatField(default=0)),
                ('waste_generated', models.FloatField(default=0)),
                ('water_usage', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('ai_verified_emissions', models.FloatField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_fraud_flag', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('ai_verified_at', models.DateTimeField(blank=True, null=True)),
                ('government_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_credits', models.IntegerField(blank=True, null=True)),
                ('assigned_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_verified', 'AI Verified'), ('government_reviewed', 'Government Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/emissions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_submissions', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emission_submissions',
            },
        ),
    ]
